---
name: Backend deployment
on:
  workflow_dispatch:
  push:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_PYTHON_BLACK: true

  test:
    runs-on: ubuntu-latest
    needs: [ linter ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: x64

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --deploy --dev

      - name: Run tests with coverage
        run: |
          pwd
          pip install coverage
          pipenv run coverage run --source "." manage.py test
        #          pipenv run coverage xml -i
        working-directory: octopus

      - name: Run tests in reverse
        run: |
          pipenv run python manage.py test --reverse
        working-directory: octopus
